[Icon Theme]
Name=Swaytastic
Comment=Swaytastic folders (green stroke, pink fill)
Inherits=Adwaita,hicolor
Directories=16x16/places,16x16/mimetypes,24x24/places,24x24/mimetypes,32x32/places,32x32/mimetypes,48x48/places,48x48/mimetypes,64x64/places,64x64/mimetypes,96x96/places,96x96/mimetypes,128x128/places,128x128/mimetypes,scalable/places,scalable/mimetypes

[16x16/places]
Size=16
Context=Places
Type=Fixed

[16x16/mimetypes]
Size=16
Context=MimeTypes
Type=Fixed

[24x24/places]
Size=24
Context=Places
Type=Fixed

[24x24/mimetypes]
Size=24
Context=MimeTypes
Type=Fixed

[32x32/places]
Size=32
Context=Places
Type=Fixed

[32x32/mimetypes]
Size=32
Context=MimeTypes
Type=Fixed

[48x48/places]
Size=48
Context=Places
Type=Fixed

[48x48/mimetypes]
Size=48
Context=MimeTypes
Type=Fixed

[64x64/places]
Size=64
Context=Places
Type=Fixed

[64x64/mimetypes]
Size=64
Context=MimeTypes
Type=Fixed

[96x96/places]
Size=96
Context=Places
Type=Fixed

[96x96/mimetypes]
Size=96
Context=MimeTypes
Type=Fixed

[128x128/places]
Size=128
Context=Places
Type=Fixed

[128x128/mimetypes]
Size=128
Context=MimeTypes
Type=Fixed

[scalable/places]
Size=48
MinSize=16
MaxSize=256
Context=Places
Type=Scalable

[scalable/mimetypes]
Size=48
MinSize=16
MaxSize=256
Context=MimeTypes
Type=Scalable
