[Icon Theme]
Name=Swaytastic
Comment=Yellow text, rainbow chrome
Inherits=Adwaita,hicolor
Directories=scalable/places,scalable/mimetypes,scalable/devices,scalable/status,symbolic/actions,symbolic/apps,symbolic/categories,symbolic/devices,symbolic/emotes,symbolic/mimetypes,symbolic/places,symbolic/status,symbolic/legacy,symbolic/ui

[scalable/places]
Size=48
MinSize=1
MaxSize=512
Context=Places
Type=Scalable

[scalable/mimetypes]
Size=48
MinSize=1
MaxSize=512
Context=MimeTypes
Type=Scalable

[scalable/devices]
Size=48
MinSize=1
MaxSize=512
Context=Devices
Type=Scalable

[scalable/status]
Size=48
MinSize=1
MaxSize=512
Context=Status
Type=Scalable

[symbolic/actions]
Size=16
MinSize=1
MaxSize=512
Context=Actions
Type=Scalable

[symbolic/apps]
Size=16
MinSize=1
MaxSize=512
Context=Applications
Type=Scalable

[symbolic/categories]
Size=16
MinSize=1
MaxSize=512
Context=Categories
Type=Scalable

[symbolic/devices]
Size=16
MinSize=1
MaxSize=512
Context=Devices
Type=Scalable

[symbolic/emotes]
Size=16
MinSize=1
MaxSize=512
Context=Emotes
Type=Scalable

[symbolic/mimetypes]
Size=16
MinSize=1
MaxSize=512
Context=MimeTypes
Type=Scalable

[symbolic/places]
Size=16
MinSize=1
MaxSize=512
Context=Places
Type=Scalable

[symbolic/status]
Size=16
MinSize=1
MaxSize=512
Context=Status
Type=Scalable

[symbolic/legacy]
Size=16
MinSize=1
MaxSize=512
Context=Legacy
Type=Scalable

[symbolic/ui]
Size=16
MinSize=1
MaxSize=512
Context=UI
Type=Scalable
